### ISSUE TITLE
TypeError: Caught TypeError in DataLoader worker process 0. in 'for batch in train_loader'  train_lm.py

### ISSUE THREAD

**Issue by Matthew-CQ** [ethnhe/FFB6D#18]
Here is the complete log:
Ubuntu18.4, only one 2080ti GPU, python packages are the same with requirement.txt.

/home/quanchen/Desktop/6dcode/FFB6D/ffb6d/common.py:139: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.lm_r_lst = yaml.load(lm_r_file)
local_rank: 0
cls_id in lm_dataset.py 6
/home/quanchen/Desktop/6dcode/FFB6D/ffb6d/datasets/linemod/linemod_dataset.py:46: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.meta_lst = yaml.load(meta_file)
render data length:  0
Warning: Trainnig without rendered data will hurt model performance 
Please generate rendered data from https://github.com/ethnhe/raster_triangle.

fused data length:  0
Warning: Trainnig without fused data will hurt model performance 
Please generate fused data from https://github.com/ethnhe/raster_triangle.

train_dataset_size:  177
cls_id in lm_dataset.py 6
test_dataset_size:  1002
loading resnet34 pretrained mdl.
local_rank: 0
Selected optimization level O0:  Pure FP32 training.

Defaults for this optimization level are:
enabled                : True
opt_level              : O0
cast_model_type        : torch.float32
patch_torch_functions  : False
keep_batchnorm_fp32    : None
master_weights         : False
loss_scale             : 1.0
Processing user overrides (additional kwargs that are not None)...
After processing overrides, optimization options are:
enabled                : True
opt_level              : O0
cast_model_type        : torch.float32
patch_torch_functions  : False
keep_batchnorm_fp32    : None
master_weights         : False
loss_scale             : 1.0
/home/quanchen/pyenv/FFB6D/lib/python3.6/site-packages/torch/nn/_reduction.py:43: UserWarning: size_average and reduce args will be deprecated, please use reduction='mean' instead.
  warnings.warn(warning.format(ret))
Totally train 1475 iters per gpu.
cat_epochs:   0%|                                                                                                                                                                | 0/25 [00:00<?, ?it/s]
train:   0%|                                                                                                                                                                    | 0/122 [00:00<?, ?it/sTraceback (most recent call last):                                                                                                                                                                       
  File "train_lm.py", line 696, in <module>
    train()
  File "train_lm.py", line 687, in train
    clr_div=clr_div
  File "train_lm.py", line 482, in train
    **for batch in train_loader:**
  File "/home/quanchen/pyenv/FFB6D/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/quanchen/pyenv/FFB6D/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/quanchen/pyenv/FFB6D/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/quanchen/pyenv/FFB6D/lib/python3.6/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
**TypeError: Caught TypeError in DataLoader worker process 0.**
Original Traceback (most recent call last):
  File "/home/quanchen/pyenv/FFB6D/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/quanchen/pyenv/FFB6D/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/quanchen/pyenv/FFB6D/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/quanchen/Desktop/6dcode/FFB6D/ffb6d/datasets/linemod/linemod_dataset.py", line 444, in __getitem__
    data = self.get_item(item_name)
  File "/home/quanchen/Desktop/6dcode/FFB6D/ffb6d/datasets/linemod/linemod_dataset.py", line 222, in get_item
    ri = self.trancolor(ri)
  File "/home/quanchen/pyenv/FFB6D/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 579, in __call__
    return transform(img)
  File "/home/quanchen/pyenv/FFB6D/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 42, in __call__
    img = t(img)
  File "/home/quanchen/pyenv/FFB6D/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 232, in __call__
    return self.lambd(img)
  File "/home/quanchen/pyenv/FFB6D/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 562, in <lambda>
    transforms.append(Lambda(lambda img: F.adjust_hue(img, hue_factor)))
  File "/home/quanchen/pyenv/FFB6D/lib/python3.6/site-packages/torchvision/transforms/functional.py", line 485, in adjust_hue
    np_h = np.array(h, dtype=np.uint8)
TypeError: __array__() takes 1 positional argument but 2 were given

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/quanchen/pyenv/FFB6D/lib/python3.6/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/home/quanchen/pyenv/FFB6D/lib/python3.6/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/quanchen/pyenv/FFB6D/bin/python3', '-u', 'train_lm.py', '--local_rank=0', '--gpus=1', '--cls=cat', '--gpu=0']' returned non-zero exit status 1.

**Comment by Matthew-CQ** [comment]
Solved. According to this [issue](https://github.com/pytorch/pytorch/issues/61125#issuecomment-872624273), just
pip install pillow==8.2.0

**Comment by Gauravajariwal11** [comment]
Hey @Matthew-CQ , I am assuming that you were able to run the model. I have an error while installing NormalSpeed and I can't figure out why. Can you help me out?
