### ISSUE TITLE
error while compiling normalSpeed

### ISSUE THREAD

**Issue by Gauravajariwal11** [ethnhe/FFB6D#23]
I have opencv3 and opencv_conrtrib installed via pip. I have pybind installed as well. I am still getting this error while I install normalSpeed. Any ideas what can be done?

/home/ubuntu/Desktop/normalSpeed_eth/normalSpeed/normalSpeed/np2mat/ndarray_converter.cpp:134:10: note:   candidate expects 3 arguments, 5 provided
/home/ubuntu/Desktop/normalSpeed_eth/normalSpeed/normalSpeed/np2mat/ndarray_converter.cpp: In static member function ‘static PyObject* NDArrayConverter::toNDArray(const cv::Mat&)’:
/home/ubuntu/Desktop/normalSpeed_eth/normalSpeed/normalSpeed/np2mat/ndarray_converter.cpp:343:12: error: ‘class cv::Mat’ has no member named ‘u’
     if(!p->u || p->allocator != &g_numpyAllocator)
            ^
/home/ubuntu/Desktop/normalSpeed_eth/normalSpeed/normalSpeed/np2mat/ndarray_converter.cpp:349:33: error: ‘class cv::Mat’ has no member named ‘u’
     PyObject* o = (PyObject*)p->u->userdata;
                                 ^
CMakeFiles/normalSpeed.dir/build.make:110: recipe for target 'CMakeFiles/normalSpeed.dir/np2mat/ndarray_converter.cpp.o' failed
make[2]: *** [CMakeFiles/normalSpeed.dir/np2mat/ndarray_converter.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/normalSpeed.dir/all' failed
make[1]: *** [CMakeFiles/normalSpeed.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 67, in <module>
    zip_safe=False,
  File "/home/ubuntu/anaconda3/envs/ffb/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/ubuntu/anaconda3/envs/ffb/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/ubuntu/anaconda3/envs/ffb/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/ubuntu/anaconda3/envs/ffb/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/ubuntu/anaconda3/envs/ffb/lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/ubuntu/anaconda3/envs/ffb/lib/python3.6/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/ubuntu/anaconda3/envs/ffb/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/ubuntu/anaconda3/envs/ffb/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/ubuntu/anaconda3/envs/ffb/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 167, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/ubuntu/anaconda3/envs/ffb/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 153, in call_command
    self.run_command(cmdname)
  File "/home/ubuntu/anaconda3/envs/ffb/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/ubuntu/anaconda3/envs/ffb/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/ubuntu/anaconda3/envs/ffb/lib/python3.6/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/ubuntu/anaconda3/envs/ffb/lib/python3.6/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/ubuntu/anaconda3/envs/ffb/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/ubuntu/anaconda3/envs/ffb/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 33, in run
    self.build_extension(ext)
  File "setup.py", line 58, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
  File "/home/ubuntu/anaconda3/envs/ffb/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j2']' returned non-zero exit status 2.

**Comment by MinWang1997** [comment]
Hi Gaurav I have the same issue with you.

Do you figure it out?

**Comment by ethnhe** [comment]
It seems the opencv3 issue. Most of the normalSpeed code is in c++ and required c++ version of opencv3.4. Try to install opencv3.4 from the source code [here](https://github.com/opencv/opencv/tree/3.4), you can clone the repo and checkout to the 3.4 branch to do that.
