### ISSUE TITLE
Error while trying to test pre-trained model

### ISSUE THREAD

**Issue by Gauravajariwal11** [ethnhe/FFB6D#31]
I downloaded the pretrained model and put it in the respective folder, still getting this error. Would be great if someone can help me here!
![Screenshot from 2021-08-31 02-37-14](https://user-images.githubusercontent.com/28729137/131462525-73e86523-6388-4c73-8597-47a07a1fa930.png)

**Comment by ethnhe** [comment]
It seems like you didn't compile the related code following our README instruction:
https://github.com/ethnhe/FFB6D#:~:text=Compile%20RandLA-Net%20operators%3A

**Comment by Gauravajariwal11** [comment]
I did compile the RANDLA operators. I have pytorch version 1.5.0 and torchvision 0.6.0. Do you think that is the error?

**Comment by HannahHaensen** [comment]
@Gauravajariwal11 hey I met the same problem. Have you solved it? 

`Traceback (most recent call last):
  File "train_lm.py", line 31, in <module>
    from models.ffb6d import FFB6D
  File "/home/user/Documents/GitHub/FFB6D/ffb6d/models/ffb6d.py", line 6, in <module>
    from models.RandLA.RandLANet import Network as RandLANet
  File "/home/user/Documents/GitHub/FFB6D/ffb6d/models/RandLA/RandLANet.py", line 5, in <module>
    from helper_tool import DataProcessing as DP
  File "/home/user/Documents/GitHub/FFB6D/ffb6d/models/RandLA/helper_tool.py", line 15, in <module>
    import nearest_neighbors.lib.python.nearest_neighbors as nearest_neighbors
ModuleNotFoundError: No module named 'nearest_neighbors.lib'; 'nearest_neighbors' is not a package
`

it compiled and also appears in the package overview

**Comment by HannahHaensen** [comment]
@Gauravajariwal11 solved it: https://github.com/ethnhe/FFB6D/issues/77
