### ISSUE TITLE
no module names NormalSpeed running demo.py

### ISSUE THREAD

**Issue by an99990** [ethnhe/FFB6D#33]
I have installed normalSpeed and tested. But when i try to run the demo, it doesnt seem to see it.
`python3 -m demo -dataset linemod -checkpoint $tst_mdl -cls $cls -show`

error message
`/home/halodi/test_2_venv/FFB6D/ffb6d/models/RandLA/helper_tool.py:252: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if dataset_name is 'S3DIS':
/home/halodi/test_2_venv/FFB6D/ffb6d/models/RandLA/helper_tool.py:255: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif dataset_name is 'Semantic3D':
/home/halodi/test_2_venv/FFB6D/ffb6d/models/RandLA/helper_tool.py:258: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif dataset_name is 'SemanticKITTI':
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/halodi/test_2_venv/FFB6D/ffb6d/demo.py", line 19, in <module>
    from datasets.ycb.ycb_dataset import Dataset as YCB_Dataset
  File "/home/halodi/test_2_venv/FFB6D/ffb6d/datasets/ycb/ycb_dataset.py", line 11, in <module>
    from utils.basic_utils import Basic_Utils
  File "/home/halodi/test_2_venv/FFB6D/ffb6d/utils/basic_utils.py", line 9, in <module>
    import normalSpeed
ModuleNotFoundError: No module named 'normalSpeed'`

please help @ethnhe 
thanks

**Comment by HannahHaensen** [comment]
Hey how did you solve the no module normalspeed error?
