### ISSUE TITLE
No module named 'ffb6d.common'; 'ffb6d' is not a package

### ISSUE THREAD

**Issue by MiriamJo** [ethnhe/FFB6D#70]
Not sure what happened or what  I did wrong. I followed the readme exactly and everything works just fine. I installes and executed all sh files and the opther repos. However, when I try to train or use the pvn3d eval utils The same error message comes up:

> Traceback (most recent call last):
>   File "train_custom.py", line 33, in <module>
>     from utils.custom_pvn3d_eval_utils_kpls import TorchEval
>   File "/home/miriam/FFB6D/ffb6d/utils/custom_pvn3d_eval_utils_kpls.py", line 9, in <module>
>     from ffb6d.common import Config
> ModuleNotFoundError: No module named 'ffb6d.common'; 'ffb6d' is not a package

I did not change the location or anything. It seems as if pycharm isn't finding common as module.
I tried marking FFB6D as root dir, also marking ffb6d as source dir , nothing changed. Maybe someone else with this problem?

**Comment by MiriamJo** [comment]
I managed to fix the error by creating a `setup.py` file in the ffb6d directory:

```
from setuptools import setup, find_packages
setup(name='ffb6d', version='1.0', packages=find_packages())
```

But its just a workaround. So for anyone searching a quick fix: this is it. Weird tho - maybe it is because i wasn't working on a virtual environment..
