### ISSUE TITLE
compile normalSpeed errors

### ISSUE THREAD

**Issue by LZL-CS** [ethnhe/FFB6D#80]
I have installed opencv3, but always get the error:
`(ffb6d) -bash-4.2$ python3 setup.py install
running install
/homes/al315/anaconda3/envs/ffb6d/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
/homes/al315/anaconda3/envs/ffb6d/lib/python3.7/site-packages/setuptools/command/easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  EasyInstallDeprecationWarning,
running bdist_egg
running egg_info
creating normalSpeed.egg-info
writing normalSpeed.egg-info/PKG-INFO
writing dependency_links to normalSpeed.egg-info/dependency_links.txt
writing top-level names to normalSpeed.egg-info/top_level.txt
writing manifest file 'normalSpeed.egg-info/SOURCES.txt'
reading manifest file 'normalSpeed.egg-info/SOURCES.txt'
writing manifest file 'normalSpeed.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found OpenCV: /import/linux/opencv/3.4.3 (found suitable version "3.4.3", minimum required is "3") 
-- Found PythonLibs: /usr/lib64/libpython3.4m.so (found suitable version "3.4.10", minimum required is "3") 
CMake Error: Error in cmake code at
/homes/al315/anaconda3/envs/ffb6d/share/cmake/pybind11/pybind11Config.cmake:3:
Parse error.  Expected a command name, got unquoted argument with text "pybind11Config.cmake".
CMake Error at CMakeLists.txt:12 (find_package):
  find_package Error reading CMake code from
  "/homes/al315/anaconda3/envs/ffb6d/share/cmake/pybind11/pybind11Config.cmake".

-- Found NumPy: /homes/al315/anaconda3/envs/ffb6d/lib/python3.7/site-packages/numpy/core/include (found version "1.21.5") 
CMake Error at CMakeLists.txt:26 (pybind11_add_module):
  Unknown CMake command "pybind11_add_module".

-- Configuring incomplete, errors occurred!
See also "/import/networks/FFB6D/normalSpeed/normalSpeed/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "setup.py", line 67, in <module>
    zip_safe=False,
  File "/homes/al315/anaconda3/envs/ffb6d/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/homes/al315/anaconda3/envs/ffb6d/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 148, in setup
    return run_commands(dist)
  File "/homes/al315/anaconda3/envs/ffb6d/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
    dist.run_commands()
  File "/homes/al315/anaconda3/envs/ffb6d/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/homes/al315/anaconda3/envs/ffb6d/lib/python3.7/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/homes/al315/anaconda3/envs/ffb6d/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/homes/al315/anaconda3/envs/ffb6d/lib/python3.7/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/homes/al315/anaconda3/envs/ffb6d/lib/python3.7/site-packages/setuptools/command/install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "/homes/al315/anaconda3/envs/ffb6d/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/homes/al315/anaconda3/envs/ffb6d/lib/python3.7/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/homes/al315/anaconda3/envs/ffb6d/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/homes/al315/anaconda3/envs/ffb6d/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 165, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/homes/al315/anaconda3/envs/ffb6d/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 151, in call_command
    self.run_command(cmdname)
  File "/homes/al315/anaconda3/envs/ffb6d/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/homes/al315/anaconda3/envs/ffb6d/lib/python3.7/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/homes/al315/anaconda3/envs/ffb6d/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/homes/al315/anaconda3/envs/ffb6d/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/homes/al315/anaconda3/envs/ffb6d/lib/python3.7/site-packages/setuptools/_distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/homes/al315/anaconda3/envs/ffb6d/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/homes/al315/anaconda3/envs/ffb6d/lib/python3.7/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/homes/al315/anaconda3/envs/ffb6d/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "setup.py", line 33, in run
    self.build_extension(ext)
  File "setup.py", line 57, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "/homes/al315/anaconda3/envs/ffb6d/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/import/networks/FFB6D/normalSpeed/normalSpeed', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/import/networks/FFB6D/normalSpeed/normalSpeed/build/lib.linux-x86_64-3.7', '-DPYTHON_EXECUTABLE=/homes/al315/anaconda3/envs/ffb6d/bin/python3', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
`

**Comment by barvin04** [comment]
Follow these set of commands in order (should work): 

a. cd normalSpeed/normalSpeed
b. pip3 install "pybind11[global]"     #as it is, including verbatim text in quotes
c. python3 setup.py install --user
